allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 119.29.29.29
  nameserver:
  - 119.29.29.29  
  fallback:
  - tls://8.8.4.4:853
  fake-ip-filter:
  - +.demonware.net