allow-lan: true
mode: rule
log-level: info
external-controller: :9090
ipv6: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  # nameserver:
  # - dhcp://en0
  fallback:
  - tls://8.8.4.4:853