port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
allow-lan: true
mode: rule
log-level: info
external-controller: :9090
ipv6: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:7874
  # nameserver:
  # - 119.29.29.29
  # - "[2402:4e00::]:53"
  # fallback:
  # - tls://8.8.4.4:853
  # - tls://[2001:4860:4860::8844]:853