allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 119.29.29.29
  nameserver:
  - 119.29.29.29  
  fallback:
  - 101.6.6.6:5353
  fake-ip-filter:
  - +.demonware.net