allow-lan: true
mode: rule
log-level: error
ipv6: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  default-nameserver:
  - 119.29.29.29
  nameserver:
  - 119.29.29.29
  fallback:
  - tls://8.8.4.4:853
  fake-ip-filter:
  - +.demonware.net
proxies:
  - {name: "网易云解锁", server: 116.62.63.25, port: 53000, type: http, udp: true}