allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  fallback:
  - 101.6.6.6:5353
  - 208.67.220.220:443
  fake-ip-filter:
  - +.demonware.net
