allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  default-nameserver:
  - 223.5.5.5
  nameserver:
  - 223.5.5.5
  fallback:
  - tls://8.8.4.4:853
  fake-ip-filter:
  - +.demonware.net