allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  nameserver:
  - dhcp://"pppoe-wan"
  - dhcp://"system"
  fallback:
  - 101.6.6.6:5353
  fake-ip-filter:
  - +.demonware.net