allow-lan: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  nameserver:
  # - dhcp://en0
  - dhcp://system
  fallback:
  - tls://8.8.4.4:853
  fake-ip-filter:
  - +.demonware.net